### ISSUE TITLE
How to build on arm, linux source and header installed from apt

### ISSUE THREAD

**Issue by idreamerhx** [openedev/linux-rtl8822cs-wifi#2]
Hi,

I want to build this dirver on s905x3 armbian. I don't have source code and config of kernel. So i install from apt.

root@amlogic:~# uname -a
Linux amlogic 5.8.16-xxx-46+ #21 SMP Sat Oct 17 22:48:49 CST 2020 aarch64 GNU/Linux

linux-source-5.8.16-meson64
linux-headers-5.8.16-sunxi64

**Comment by openedev** [comment]
Do you have modules in /lib/modules/ and toolchain on target. If yes, you can try to build from target itself.

This respository focus only on building drivers at host.
